%% Attribute names for CIM-XML

-define(CIMVERSION, 'CIMVERSION').
-define(DTDVERSION, 'DTDVERSION').
-define(ID, 'ID').
-define(PROTOCOLVERSION, 'PROTOCOLVERSION').
-define(NAME, 'NAME').
-define(VALUETYPE, 'VALUETYPE').
-define(TYPE, 'TYPE').
-define(SUPERCLASS, 'SUPERCLASS').
-define(PROPAGATED, 'PROPAGATED').
-define(CLASSORIGIN, 'CLASSORIGIN').
-define(ARRAYSIZE, 'ARRAYSIZE').
-define(REFERENCECLASS, 'REFERENCECLASS').
-define(CLASSNAME, 'CLASSNAME').
-define(CODE, 'CODE').
-define(DESCRIPTION, 'DESCRIPTION').
-define(PARAMTYPE, 'PARAMTYPE').
-define(ISARRAY, 'ISARRAY').

-define(CLASS, 'CLASS').
-define(ASSOCIATION, 'ASSOCIATION').
-define(REFERENCE, 'REFERENCE').
-define(PROPERTY, 'PROPERTY').
-define(METHOD, 'METHOD').
-define(PARAMETER, 'PARAMETER').
-define(INDICATION, 'INDICATION').

-define(OVERRIDABLE, 'OVERRIDABLE').
-define(TOSUBCLASS, 'TOSUBCLASS').
-define(TOINSTANCE, 'TOINSTANCE').
-define(TRANSLATABLE, 'TRANSLATABLE').
